---
- name: Find .properties files and compare
  hosts: localhost
  gather_facts: no

  environment:
    ANSIBLE_DISPLAY_SKIPPED_HOSTS: "False"

  tasks:        
    - name: create temp file
      tempfile:
        state:  file
        prefix: compare_results
      register: temp_config

    - name: set tempfile path
      set_fact:
        tmp_file: "{{ temp_config.path }}"
          
    - debug: var=tmp_file
    - name: Find .properties files
      find:
        paths: C:/cygwin64/home/bindu/playbooks/naveen/prod
        patterns: "*.*"
        recurse: yes
      register: prop_files

    - name: check if file exists and compare
      vars:
        file_name: "{{ item.split('/')[-1] }}"
        file_src_path: "{{ item }}"
      include_tasks: compare.yml
      loop: "{{ prop_files.files | map(attribute='path') | list }}"

    - shell: "cat {{ tmp_file }}"
      register: compare_content

    - debug: 
        msg: "{{ compare_content.stdout_lines }}"
      
   