---
- name: Get first key-value pair from dictionary
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Define the dictionary
      set_fact:
        my_dict:
          key1: value1
          key2: value2
          key3: value3

    - name: Convert dictionary to key-value pairs list
      set_fact:
        dict_items: "{{ my_dict | dict2items }}"

    - name: Get the first key-value pair
      set_fact:
        first_key_value_pair: "{{ dict_items | first }}"

    - name: Display the first key-value pair
      debug:
        var: first_key_value_pair
